# Generated by Django 3.1.2 on 2022-01-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_multa', models.DateField(auto_now_add=True, verbose_name='Data da Multa')),
                ('data_limite', models.DateField(verbose_name='Data da Multa')),
                ('pagou', models.BooleanField(verbose_name='Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('ra', models.CharField(max_length=50, verbose_name='RA')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('informacoes_adcionais', models.CharField(max_length=50, verbose_name='Informações Adcionais')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='Data da Retirada')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('data_devolucao', models.DateField(verbose_name='Data da Devolução')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuário')),
                ('objeto_emprestado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.objeto', verbose_name='Objeto Emprestado')),
            ],
        ),
    ]
