# Generated by Django 3.2.9 on 2021-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='Data da Retirada')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('data_devolucao', models.DateField(verbose_name='Data da Devolução')),
                ('objeto_emprestado', models.CharField(max_length=50, verbose_name='Objeto Emprestado')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(max_length=50, verbose_name='Valor')),
                ('data_multa', models.DateField(verbose_name='Data da Multa')),
                ('pagou', models.BooleanField(verbose_name='Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado', models.BooleanField(verbose_name='Emprestado')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('informacoes_adcionais', models.CharField(max_length=50, verbose_name='Informações Adcionais')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('ra', models.CharField(max_length=50, verbose_name='RA')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
    ]
